[build]
target-dir = "../../../dist/apps/desktop/target"

[term]
quiet = false          # whether cargo output is quiet
verbose = false        # whether cargo provides verbose output
color = 'auto'         # whether cargo colorizes output
# progress.when = 'auto' # whether cargo shows progress bar
# progress.width = 80    # width of progress bar